steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'eu.gcr.io/test-hellotwin/mailer-image-168:${SHORT_SHA}', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'eu.gcr.io/test-hellotwin/mailer-image-168:${SHORT_SHA}']
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - send-build-alerts
      - --project=test-hellotwin
      - --image=eu.gcr.io/test-hellotwin/mailer-image-168:${SHORT_SHA}
      - --region=europe-central2
      - --platform=managed
      - --no-allow-unauthenticated
#    secretEnv: ['USR', 'PWD']
#availableSecrets:
#    secretManager:
#      - versionName: projects/636510427510/secrets/sender-s_id/versions/1
#        env: USR
#      - versionName: projects/636510427510/secrets/sender-s_secret/versions/1
#        env: PWD
