steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/PROJECT_NAME/notifier-image:${SHORT_SHA}', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/PROJECT_NAME/notifier-image:${SHORT_SHA}']
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - send-build-alerts
      - --project=PROJECT_NAME
      - --image=gcr.io/PROJECT_NAME/notifier-image:${SHORT_SHA}
      - --region=europe-central1
      - --platform=managed
      - --no-allow-unauthenticated
#    secretEnv: ['USR', 'PWD']
#availableSecrets:
#    secretManager:
#      - versionName: projects/636510427510/secrets/sender1/versions
#        env: USR
#      - versionName: projects/636510427510/secrets/secret2/versions
#        env: PWD
