steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'eu.gcr.io/test-hellotwin/mailer-image:${SHORT_SHA}', '.']
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - '/bin/sh'
      - '-c'
      - |
        echo $$msmtp-pswd > /dev/null
        echo "body" | mutt -s "A mail from GCB" -- u.aliakhnovich@sam-solutions.com
    secretEnv: [msmtp-pswd]
availableSecrets:
  secretManager:
    - versionName:  projects/636510427510/secrets/msmtp-pswd/latest
      env: msmtp-pswd
